"""Initial AlloyDB schema for Aegis — 14 tables.

Revision ID: 001
Revises: None
Create Date: 2026-04-05

Tables (Phase 1 core + Phase 2 stubs):
  Phase 1 (9 tables):
    workspaces            — Workspace entity + control_level + github_repo (Phase 6)
    bets                  — Bet entity + health_baseline (JSONB)
    bet_snapshots         — LinearSignals capture (JSONB) + health_score
    risk_signals          — Classified risk signals from Product Brain
    interventions         — Proposed + actioned interventions from Coordinator
    outcomes              — Post-intervention outcome records
    agent_traces          — ADK trace log for AutoResearch (input_context_hash)
    heuristic_versions    — Versioned Constitution (MAJOR/MINOR/PATCH)
    policy_denied_events  — Governor denial log (Phase 2: surface to AutoResearch)

  Phase 2 stubs (5 tables — created now, populated Phase 2):
    product_heuristics          — ProductHeuristic corpus (Lenny, Shreyas, etc.)
    bet_rejections              — Rejected bet declarations
    hypothesis_experiments      — Hypothesis staleness tracking
    rejection_reason_clusters   — NLP-extracted rejection clusters for AutoResearch
    startup_failure_patterns    — IdeaProof failure corpus; embedding col added when pgvector activated

Design notes:
  - All IDs are UUID (TEXT, generated by application layer with uuid4())
  - Timestamps are TIMESTAMPTZ (UTC)
  - JSONB used for nested structures (linear_signals, metrics, evidence)
    to preserve schema flexibility during Phase 1 iteration
  - pgvector extension not created here — added as a separate migration
    when AlloyDB vector search is activated in Phase 3
  - Foreign key constraints added within Phase 1 tables only; Phase 2 stubs
    are lightly constrained to allow independent testing
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ─────────────────────────────────────────────
    # PHASE 1 — CORE TABLES
    # ─────────────────────────────────────────────

    # 1. workspaces
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("linear_team_id", sa.Text(), nullable=False),
        sa.Column(
            "strategy_doc_refs",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "active_bet_ids", sa.ARRAY(sa.Text()), nullable=False, server_default="{}"
        ),
        # ControlLevel: 'draft_only' | 'require_approval' | 'autonomous_low_risk'
        sa.Column(
            "control_level", sa.Text(), nullable=False, server_default="draft_only"
        ),
        # Phase 6: github_repo — Governor jules_gate (check #4) reads this.
        # NULL until founder connects GitHub via Settings UI.
        sa.Column("github_repo", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_workspaces"),
    )
    op.create_index("ix_workspaces_linear_team_id", "workspaces", ["linear_team_id"])

    # 2. bets
    op.create_table(
        "bets",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("target_segment", sa.Text(), nullable=False),
        sa.Column("problem_statement", sa.Text(), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False, server_default=""),
        # Stored as JSONB: [{name, target_value, unit, current_value}]
        sa.Column("success_metrics", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("time_horizon", sa.Text(), nullable=False),
        # DeclarationSource: {type, linear_project_id, raw_artifact_refs}
        sa.Column("declaration_source", sa.JSON(), nullable=False),
        sa.Column("declaration_confidence", sa.Float(), nullable=False),
        # BetStatus: 'detecting' | 'active' | 'paused' | 'validated' | 'killed'
        sa.Column("status", sa.Text(), nullable=False, server_default="active"),
        # BetHealthBaseline: {expected_bet_coverage_pct, expected_weekly_velocity,
        #                     hypothesis_required, metric_linked_required}
        sa.Column("health_baseline", sa.JSON(), nullable=False),
        # AcknowledgedRisk[]: [{risk_type, acknowledged_at, founder_note}]
        sa.Column("acknowledged_risks", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column(
            "linear_project_ids",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "linear_issue_ids", sa.ARRAY(sa.Text()), nullable=False, server_default="{}"
        ),
        sa.Column("doc_refs", sa.ARRAY(sa.Text()), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_monitored_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_bets"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name="fk_bets_workspace_id"
        ),
    )
    op.create_index("ix_bets_workspace_id", "bets", ["workspace_id"])
    op.create_index("ix_bets_status", "bets", ["status"])
    op.create_index("ix_bets_last_monitored_at", "bets", ["last_monitored_at"])

    # 3. bet_snapshots
    op.create_table(
        "bet_snapshots",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("bet_id", sa.Text(), nullable=False),
        sa.Column("captured_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("period_start", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("period_end", sa.TIMESTAMP(timezone=True), nullable=False),
        # LinearSignals stored as JSONB — all scalar fields from LinearSignals model
        sa.Column("linear_signals", sa.JSON(), nullable=False),
        sa.Column("health_score", sa.Float(), nullable=False),
        # risk_types_present: list of detected risk types (pre-filter, not classification)
        sa.Column(
            "risk_types_present",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        # ScanStatus: 'ok' | 'error'
        sa.Column("status", sa.Text(), nullable=False, server_default="ok"),
        # ScanErrorCode: 'rate_limit' | 'auth_expired' | 'api_timeout' | 'empty_workspace'
        sa.Column("error_code", sa.Text(), nullable=True),
        # Phase 2: null = not computed. 0 = tested today. NEVER default to 0.
        sa.Column("hypothesis_staleness_days", sa.Integer(), nullable=True),
        sa.Column(
            "hypothesis_experiment_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column("last_experiment_outcome", sa.Text(), nullable=True),
        # Phase 3: cross-workspace outcome signals
        sa.Column("similar_bet_outcome_pct", sa.Float(), nullable=True),
        sa.Column(
            "outcome_pattern_source_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        # Phase 2: between-cycle cache invalidation
        sa.Column("cache_valid_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_bet_snapshots"),
        sa.ForeignKeyConstraint(
            ["bet_id"], ["bets.id"], name="fk_bet_snapshots_bet_id"
        ),
    )
    op.create_index("ix_bet_snapshots_bet_id", "bet_snapshots", ["bet_id"])
    op.create_index("ix_bet_snapshots_captured_at", "bet_snapshots", ["captured_at"])
    op.create_index(
        "ix_bet_snapshots_bet_id_captured_at",
        "bet_snapshots",
        ["bet_id", sa.text("captured_at DESC")],
    )

    # 4. risk_signals
    op.create_table(
        "risk_signals",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("bet_id", sa.Text(), nullable=False),
        sa.Column("snapshot_id", sa.Text(), nullable=False),
        # RiskType: 'strategy_unclear' | 'alignment_issue' | 'execution_issue' | 'placebo_productivity'
        sa.Column("risk_type", sa.Text(), nullable=False),
        # Severity: 'low' | 'medium' | 'high' | 'critical'
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        # Evidence[]: [{type, description, linear_refs, observed_value, threshold_value, period_days}]
        sa.Column("evidence", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("evidence_summary", sa.Text(), nullable=False, server_default=""),
        sa.Column(
            "product_principle_refs",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        # Status: 'open' | 'actioned' | 'resolved' | 'dismissed'
        sa.Column("status", sa.Text(), nullable=False, server_default="open"),
        sa.Column("detected_by", sa.Text(), nullable=False),  # agent name
        sa.Column("detected_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_risk_signals"),
        sa.ForeignKeyConstraint(["bet_id"], ["bets.id"], name="fk_risk_signals_bet_id"),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["bet_snapshots.id"], name="fk_risk_signals_snapshot_id"
        ),
    )
    op.create_index("ix_risk_signals_bet_id", "risk_signals", ["bet_id"])
    op.create_index("ix_risk_signals_risk_type", "risk_signals", ["risk_type"])
    op.create_index("ix_risk_signals_status", "risk_signals", ["status"])
    op.create_index("ix_risk_signals_detected_at", "risk_signals", ["detected_at"])

    # 5. interventions
    op.create_table(
        "interventions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column(
            "risk_signal_id", sa.Text(), nullable=True
        ),  # nullable: no-intervention records
        sa.Column("bet_id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        # ActionType — full taxonomy (L1/L2/L3/L4 + special)
        sa.Column("action_type", sa.Text(), nullable=False),
        # EscalationLevel: 1 | 2 | 3 | 4
        sa.Column("escalation_level", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "product_principle_refs",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        # LinearAction: {add_label, add_comment, create_issue, update_status, draft_document}
        sa.Column("proposed_linear_action", sa.JSON(), nullable=True),
        # BlastRadiusPreview: {affected_issue_count, affected_assignee_ids, ...}
        sa.Column("blast_radius", sa.JSON(), nullable=True),
        # InterventionStatus: 'pending' | 'accepted' | 'rejected' | 'dismissed'
        sa.Column("status", sa.Text(), nullable=False, server_default="pending"),
        sa.Column("decided_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("founder_note", sa.Text(), nullable=True),
        # RejectionReasonCategory: 'evidence_too_weak' | 'already_handled' | ...
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_interventions"),
        sa.ForeignKeyConstraint(
            ["bet_id"], ["bets.id"], name="fk_interventions_bet_id"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name="fk_interventions_workspace_id"
        ),
    )
    op.create_index("ix_interventions_bet_id", "interventions", ["bet_id"])
    op.create_index("ix_interventions_status", "interventions", ["status"])
    op.create_index("ix_interventions_action_type", "interventions", ["action_type"])
    op.create_index("ix_interventions_created_at", "interventions", ["created_at"])
    # For duplicate suppression check: (bet_id, action_type, status)
    op.create_index(
        "ix_interventions_bet_action_status",
        "interventions",
        ["bet_id", "action_type", "status"],
    )

    # 6. outcomes
    op.create_table(
        "outcomes",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("intervention_id", sa.Text(), nullable=False),
        sa.Column("bet_id", sa.Text(), nullable=False),
        sa.Column("snapshot_before_id", sa.Text(), nullable=False),
        sa.Column("snapshot_after_id", sa.Text(), nullable=False),
        sa.Column("health_score_delta", sa.Float(), nullable=False),
        sa.Column("risk_resolved", sa.Boolean(), nullable=False),
        sa.Column("founder_rating", sa.Integer(), nullable=True),  # 1-5
        sa.Column("measured_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_outcomes"),
        sa.ForeignKeyConstraint(
            ["intervention_id"],
            ["interventions.id"],
            name="fk_outcomes_intervention_id",
        ),
        sa.ForeignKeyConstraint(["bet_id"], ["bets.id"], name="fk_outcomes_bet_id"),
    )
    op.create_index("ix_outcomes_intervention_id", "outcomes", ["intervention_id"])
    op.create_index("ix_outcomes_bet_id", "outcomes", ["bet_id"])

    # 7. agent_traces
    op.create_table(
        "agent_traces",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        # TraceType: 'bet_clustering' | 'risk_detection' | 'risk_classification' |
        #            'intervention_selection' | 'linear_write'
        sa.Column("trace_type", sa.Text(), nullable=False),
        sa.Column("agent_name", sa.Text(), nullable=False),
        # sha256(json.dumps({"bet_id", "signals" (exclude read_window_days), "heuristic_version"},
        #   sort_keys=True)) — never includes timestamps, workspace_id, or session metadata.
        sa.Column("input_context_hash", sa.Text(), nullable=False),
        sa.Column("output_summary", sa.Text(), nullable=False),
        sa.Column(
            "output_ids", sa.ARRAY(sa.Text()), nullable=False, server_default="{}"
        ),
        # Phase 3: chain-of-thought before classification
        sa.Column("classification_rationale", sa.Text(), nullable=True),
        sa.Column("heuristic_version_id", sa.Text(), nullable=False),
        sa.Column("eval_score", sa.Float(), nullable=True),
        sa.Column("eval_rubric", sa.Text(), nullable=True),
        sa.Column("human_accepted", sa.Boolean(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_agent_traces"),
    )
    op.create_index("ix_agent_traces_workspace_id", "agent_traces", ["workspace_id"])
    op.create_index("ix_agent_traces_trace_type", "agent_traces", ["trace_type"])
    op.create_index(
        "ix_agent_traces_input_context_hash", "agent_traces", ["input_context_hash"]
    )
    op.create_index(
        "ix_agent_traces_heuristic_version_id", "agent_traces", ["heuristic_version_id"]
    )
    op.create_index("ix_agent_traces_created_at", "agent_traces", ["created_at"])

    # 8. heuristic_versions (Versioned Constitution)
    op.create_table(
        "heuristic_versions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),  # semver e.g. "1.0.0"
        # HeuristicVersionStatus: 'candidate' | 'active' | 'reverted'
        sa.Column("status", sa.Text(), nullable=False, server_default="candidate"),
        # RiskThresholds JSON: all threshold fields
        sa.Column("risk_thresholds", sa.JSON(), nullable=False),
        sa.Column("classification_prompt_fragment", sa.Text(), nullable=False),
        # InterventionWeight[]: [{action_type, weight}]
        sa.Column(
            "intervention_ranking_weights",
            sa.JSON(),
            nullable=False,
            server_default="[]",
        ),
        sa.Column("eval_score", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("acceptance_rate", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("resolution_rate", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column(
            "false_positive_rate", sa.Float(), nullable=False, server_default="0.0"
        ),
        # VersionType: 'MAJOR' | 'MINOR' | 'PATCH' — MAJOR never auto-promoted
        sa.Column("version_type", sa.Text(), nullable=False, server_default="MINOR"),
        sa.Column(
            "requires_manual_review",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
        sa.Column("git_commit_sha", sa.Text(), nullable=True),
        sa.Column("parent_version_id", sa.Text(), nullable=True),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("activated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("reverted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_heuristic_versions"),
    )
    op.create_index("ix_heuristic_versions_status", "heuristic_versions", ["status"])
    op.create_index("ix_heuristic_versions_version", "heuristic_versions", ["version"])

    # 9. policy_denied_events (Governor denial log)
    op.create_table(
        "policy_denied_events",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("bet_id", sa.Text(), nullable=False),
        sa.Column("intervention_id", sa.Text(), nullable=False),
        # PolicyDenialReason: 'confidence_below_floor' | 'duplicate_suppression' | 'rate_cap' |
        #   'jules_gate' | 'reversibility_check' | 'acknowledged_risk' |
        #   'override_teach_suppression' | 'escalation_ladder'
        sa.Column("denial_reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_policy_denied_events"),
        sa.ForeignKeyConstraint(
            ["bet_id"], ["bets.id"], name="fk_policy_denied_events_bet_id"
        ),
    )
    op.create_index(
        "ix_policy_denied_events_bet_id", "policy_denied_events", ["bet_id"]
    )
    op.create_index(
        "ix_policy_denied_events_denial_reason",
        "policy_denied_events",
        ["denial_reason"],
    )

    # ─────────────────────────────────────────────
    # PHASE 2 STUBS — created now, populated Phase 2
    # ─────────────────────────────────────────────

    # 10. product_heuristics (ProductHeuristic corpus)
    op.create_table(
        "product_heuristics",
        sa.Column("id", sa.Text(), nullable=False),
        # Source: 'lenny' | 'shreyas' | 'tigers_elephants' | 'pmf_patterns' | 'custom'
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column(
            "risk_types", sa.ARRAY(sa.Text()), nullable=False, server_default="{}"
        ),
        sa.Column("principle", sa.Text(), nullable=False),
        sa.Column("example_pattern", sa.Text(), nullable=False),
        sa.Column("suggested_action", sa.Text(), nullable=False),
        sa.Column("confidence_weight", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_product_heuristics"),
    )
    op.create_index("ix_product_heuristics_source", "product_heuristics", ["source"])

    # 11. bet_rejections (rejected bet declarations)
    op.create_table(
        "bet_rejections",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column(
            "raw_artifact_refs",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("proposed_name", sa.Text(), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("rejected_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_bet_rejections"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name="fk_bet_rejections_workspace_id"
        ),
    )
    op.create_index(
        "ix_bet_rejections_workspace_id", "bet_rejections", ["workspace_id"]
    )

    # 12. hypothesis_experiments (Phase 2: staleness detection)
    op.create_table(
        "hypothesis_experiments",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("bet_id", sa.Text(), nullable=False),
        sa.Column("hypothesis_text", sa.Text(), nullable=False),
        # ExperimentType: 'interview' | 'ab_test' | 'fake_door' | 'prototype' | 'analytics' | 'survey'
        sa.Column("experiment_type", sa.Text(), nullable=False),
        # ExperimentOutcome: 'confirmed' | 'refuted' | 'inconclusive' | 'abandoned'
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("confidence_before", sa.Float(), nullable=False),
        sa.Column("confidence_after", sa.Float(), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        # created_by: 'founder' | 'agent_draft'
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_hypothesis_experiments"),
        sa.ForeignKeyConstraint(
            ["bet_id"], ["bets.id"], name="fk_hypothesis_experiments_bet_id"
        ),
    )
    op.create_index(
        "ix_hypothesis_experiments_bet_id", "hypothesis_experiments", ["bet_id"]
    )
    op.create_index(
        "ix_hypothesis_experiments_outcome", "hypothesis_experiments", ["outcome"]
    )

    # 13. rejection_reason_clusters (Phase 2: NLP extraction for AutoResearch)
    op.create_table(
        "rejection_reason_clusters",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("cluster_label", sa.Text(), nullable=False),
        sa.Column(
            "intervention_types_affected",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "risk_types_affected",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("frequency", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "heuristic_change_candidates",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_rejection_reason_clusters"),
    )
    op.create_index(
        "ix_rejection_reason_clusters_cluster_label",
        "rejection_reason_clusters",
        ["cluster_label"],
    )

    # 14. startup_failure_patterns (Phase 2: IdeaProof ingest)
    # embedding column NOT added here — added as a separate migration when
    # pgvector extension is activated on AlloyDB (requires CREATE EXTENSION vector).
    op.create_table(
        "startup_failure_patterns",
        sa.Column("id", sa.Text(), nullable=False),
        # failure_category: 'no_market_need' | 'cash' | 'team' | 'competition' | 'timing' | 'execution'
        sa.Column("failure_category", sa.Text(), nullable=False),
        # signal_fingerprint: list of EvidenceType values observed before failure
        sa.Column(
            "signal_fingerprint",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("frequency_pct", sa.Float(), nullable=False),
        sa.Column("avg_time_to_failure_days", sa.Float(), nullable=True),
        # source: 'cb_insights' | 'failory' | 'ideaproof' | 'internal_corpus'
        sa.Column("source", sa.Text(), nullable=False),
        # Phase 2: embedding column added via separate migration when pgvector activated
        # ALTER TABLE startup_failure_patterns ADD COLUMN embedding vector(768);
        sa.PrimaryKeyConstraint("id", name="pk_startup_failure_patterns"),
    )
    op.create_index(
        "ix_startup_failure_patterns_failure_category",
        "startup_failure_patterns",
        ["failure_category"],
    )
    op.create_index(
        "ix_startup_failure_patterns_source",
        "startup_failure_patterns",
        ["source"],
    )


def downgrade() -> None:
    # Drop in reverse order of foreign key dependencies
    op.drop_table("startup_failure_patterns")
    op.drop_table("rejection_reason_clusters")
    op.drop_table("hypothesis_experiments")
    op.drop_table("bet_rejections")
    op.drop_table("product_heuristics")
    op.drop_table("policy_denied_events")
    op.drop_table("heuristic_versions")
    op.drop_table("agent_traces")
    op.drop_table("outcomes")
    op.drop_table("interventions")
    op.drop_table("risk_signals")
    op.drop_table("bet_snapshots")
    op.drop_table("bets")
    op.drop_table("workspaces")
